package clientesoap.ups;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2020-01-20T12:36:00.628-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://servicios/", name = "CuentaServiceSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface CuentaServiceSOAP {

    @WebMethod
    @RequestWrapper(localName = "crearCuenta", targetNamespace = "http://servicios/", className = "clientesoap.ups.CrearCuenta")
    @ResponseWrapper(localName = "crearCuentaResponse", targetNamespace = "http://servicios/", className = "clientesoap.ups.CrearCuentaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public clientesoap.ups.Respuesta crearCuenta(
        @WebParam(name = "arg0", targetNamespace = "")
        clientesoap.ups.Cuenta arg0
    );
}
