package clientesoap.ups;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2020-01-20T12:36:00.636-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "CuentaServiceSOAPService", 
                  wsdlLocation = "http://localhost:8080/practicaWS/CuentaServiceSOAP?wsdl",
                  targetNamespace = "http://servicios/") 
public class CuentaServiceSOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicios/", "CuentaServiceSOAPService");
    public final static QName CuentaServiceSOAPPort = new QName("http://servicios/", "CuentaServiceSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/practicaWS/CuentaServiceSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CuentaServiceSOAPService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/practicaWS/CuentaServiceSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CuentaServiceSOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CuentaServiceSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CuentaServiceSOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CuentaServiceSOAPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CuentaServiceSOAPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CuentaServiceSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CuentaServiceSOAP
     */
    @WebEndpoint(name = "CuentaServiceSOAPPort")
    public CuentaServiceSOAP getCuentaServiceSOAPPort() {
        return super.getPort(CuentaServiceSOAPPort, CuentaServiceSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CuentaServiceSOAP
     */
    @WebEndpoint(name = "CuentaServiceSOAPPort")
    public CuentaServiceSOAP getCuentaServiceSOAPPort(WebServiceFeature... features) {
        return super.getPort(CuentaServiceSOAPPort, CuentaServiceSOAP.class, features);
    }

}
