
package clientesoap.ups;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2020-01-20T12:36:00.592-05:00
 * Generated source version: 2.7.18
 * 
 */
public final class CuentaServiceSOAP_CuentaServiceSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://servicios/", "CuentaServiceSOAPService");

    private CuentaServiceSOAP_CuentaServiceSOAPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CuentaServiceSOAPService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CuentaServiceSOAPService ss = new CuentaServiceSOAPService(wsdlURL, SERVICE_NAME);
        CuentaServiceSOAP port = ss.getCuentaServiceSOAPPort();  
        
        {
        System.out.println("CrearCuenta...");
        clientesoap.ups.Cuenta cuenta = new Cuenta();
        cuenta.setCedulaCuenta("1472583690");
        cuenta.setNombresPersonaCuenta("Xavier");
        cuenta.setApellidosPersonaCuenta("Bbc");
        cuenta.setSaldoCuenta(5000);
        clientesoap.ups.Respuesta _crearCuenta__return = port.crearCuenta(cuenta);
        System.out.println("Se Creo Con Exito=" + _crearCuenta__return);

        }

        System.exit(0);
    }

}
