package clientesoap.ups;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2020-01-20T12:36:17.860-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://servicios/", name = "MovimientoServiceSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface MovimientoServiceSOAP {

    @WebMethod
    @RequestWrapper(localName = "realizarTransferencia", targetNamespace = "http://servicios/", className = "clientesoap.ups.RealizarTransferencia")
    @ResponseWrapper(localName = "realizarTransferenciaResponse", targetNamespace = "http://servicios/", className = "clientesoap.ups.RealizarTransferenciaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public clientesoap.ups.Respuesta realizarTransferencia(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );
}
