package clientesoap.ups;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2020-01-20T12:36:17.868-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "MovimientoServiceSOAPService", 
                  wsdlLocation = "file:/C:/Users/JOHNHE~1/AppData/Local/Temp/tempdir7298983142948035707.tmp/MovimientoServiceSOAP_1.wsdl",
                  targetNamespace = "http://servicios/") 
public class MovimientoServiceSOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicios/", "MovimientoServiceSOAPService");
    public final static QName MovimientoServiceSOAPPort = new QName("http://servicios/", "MovimientoServiceSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/JOHNHE~1/AppData/Local/Temp/tempdir7298983142948035707.tmp/MovimientoServiceSOAP_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MovimientoServiceSOAPService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/JOHNHE~1/AppData/Local/Temp/tempdir7298983142948035707.tmp/MovimientoServiceSOAP_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MovimientoServiceSOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MovimientoServiceSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MovimientoServiceSOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MovimientoServiceSOAPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MovimientoServiceSOAPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MovimientoServiceSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MovimientoServiceSOAP
     */
    @WebEndpoint(name = "MovimientoServiceSOAPPort")
    public MovimientoServiceSOAP getMovimientoServiceSOAPPort() {
        return super.getPort(MovimientoServiceSOAPPort, MovimientoServiceSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MovimientoServiceSOAP
     */
    @WebEndpoint(name = "MovimientoServiceSOAPPort")
    public MovimientoServiceSOAP getMovimientoServiceSOAPPort(WebServiceFeature... features) {
        return super.getPort(MovimientoServiceSOAPPort, MovimientoServiceSOAP.class, features);
    }

}
